# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpnrsUserHome.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from rpnrsMonitoring import *
from rpnrsUserInfo import *
from rpnrsReports import *
from rpnrsAdminSettings import *
from rpnrsLogin import *

class Ui_rpnrsHomeUser(object):
    def monitoring(self):
        print("Monitoring Form")
        self.rpnrsMonitoringWindow=QtWidgets.QMainWindow()
        self.ui=Ui_MainWindowMonitor()
        self.ui.setupUi4(self.rpnrsMonitoringWindow)
        self.rpnrsMonitoringWindow.show()
    def info(self):
        print("Information Form")
        self.rpnrsUserInfoWindow=QtWidgets.QMainWindow()
        self.ui=Ui_userInformationWindow()
        self.ui.setupUi5(self.rpnrsUserInfoWindow)
        self.rpnrsUserInfoWindow.show()
        self.ui.refresh()
    def report(self):
        print("View Reports")
        self.rpnrsReportsWindow=QtWidgets.QMainWindow()
        self.ui=Ui_ReportsWindow()
        self.ui.setupUi6(self.rpnrsReportsWindow)
        self.rpnrsReportsWindow.show()
        self.ui.refresh()
    def settings(self):
        print("Settings")
        self.rpnrsAdminSettingsWindow=QtWidgets.QMainWindow()
        self.ui=Ui_AdminSettingsWindow()
        self.ui.setupUi8(self.rpnrsAdminSettingsWindow)
        self.rpnrsAdminSettingsWindow.show()
    def logout(self):
        print("Logout")
        self.rpnrsLoginWindow=QtWidgets.QMainWindow()
        self.ui=Ui_LoginWindow()
        self.ui.setupUi1(self.rpnrsLoginWindow)
        self.rpnrsLoginWindow.show()
    def setupUi3(self, rpnrsHomeUser):
        rpnrsHomeUser.setObjectName("rpnrsHomeUser")
        rpnrsHomeUser.resize(935, 471)
        rpnrsHomeUser.setMinimumSize(QtCore.QSize(935, 471))
        rpnrsHomeUser.setMaximumSize(QtCore.QSize(935, 471))
        rpnrsHomeUser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblPPSS = QtWidgets.QLabel(rpnrsHomeUser)
        self.lblPPSS.setGeometry(QtCore.QRect(500, 126, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblPPSS.setFont(font)
        self.lblPPSS.setStyleSheet("color: rgb(0, 84, 139);\n"
"font: 12pt \"Century Gothic\";")
        self.lblPPSS.setObjectName("lblPPSS")
        self.line = QtWidgets.QFrame(rpnrsHomeUser)
        self.line.setGeometry(QtCore.QRect(500, 148, 271, 16))
        self.line.setStyleSheet("color: rgb(0, 84, 139);\n"
"font: 12pt \"Century Gothic\";")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_6.setGeometry(QtCore.QRect(650, 190, 171, 41))
        self.label_6.setStyleSheet("background-color: rgb(0, 84, 139);\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_5.setGeometry(QtCore.QRect(360, 190, 191, 41))
        self.label_5.setStyleSheet("background-color: rgb(0, 84, 139);\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_11.setGeometry(QtCore.QRect(479, 37, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_14 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_14.setGeometry(QtCore.QRect(660, 250, 241, 191))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setStyleSheet("color: rgb(0, 84, 139);")
        self.label_14.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_14.setLineWidth(4)
        self.label_14.setMidLineWidth(0)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_10.setGeometry(QtCore.QRect(542, 3, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_9.setGeometry(QtCore.QRect(370, 250, 241, 191))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("color: rgb(0, 84, 139);")
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setLineWidth(4)
        self.label_9.setMidLineWidth(0)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_13.setGeometry(QtCore.QRect(468, 84, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_12 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_12.setGeometry(QtCore.QRect(470, 60, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_7.setGeometry(QtCore.QRect(360, 240, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(0, 84, 139);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(rpnrsHomeUser)
        self.frame.setGeometry(QtCore.QRect(0, 0, 321, 471))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(0, 84, 139);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblRegistered = QtWidgets.QLabel(self.frame)
        self.lblRegistered.setGeometry(QtCore.QRect(49, 2, 171, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRegistered.setFont(font)
        self.lblRegistered.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblRegistered.setTextFormat(QtCore.Qt.RichText)
        self.lblRegistered.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRegistered.setObjectName("lblRegistered")
        self.lblPlateNumber = QtWidgets.QLabel(self.frame)
        self.lblPlateNumber.setGeometry(QtCore.QRect(40, 62, 251, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblPlateNumber.setFont(font)
        self.lblPlateNumber.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblPlateNumber.setTextFormat(QtCore.Qt.RichText)
        self.lblPlateNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPlateNumber.setObjectName("lblPlateNumber")
        self.lblRecognition = QtWidgets.QLabel(self.frame)
        self.lblRecognition.setGeometry(QtCore.QRect(37, 122, 221, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRecognition.setFont(font)
        self.lblRecognition.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblRecognition.setTextFormat(QtCore.Qt.RichText)
        self.lblRecognition.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRecognition.setObjectName("lblRecognition")
        self.lblSystem = QtWidgets.QLabel(self.frame)
        self.lblSystem.setGeometry(QtCore.QRect(19, 177, 180, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSystem.setFont(font)
        self.lblSystem.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblSystem.setTextFormat(QtCore.Qt.RichText)
        self.lblSystem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSystem.setObjectName("lblSystem")
        self.btnMonitoring = QtWidgets.QPushButton(self.frame)
        self.btnMonitoring.setGeometry(QtCore.QRect(0, 308, 321, 31))
        self.btnMonitoring.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMonitoring.setStyleSheet("color: rgb(0, 84, 139);\n"
"background-color: rgb(218, 218, 218);\n"
"font: 9pt \"Century Gothic\";")
        self.btnMonitoring.setAutoDefault(True)
        self.btnMonitoring.setDefault(False)
        self.btnMonitoring.setFlat(False)
        self.btnMonitoring.setObjectName("btnMonitoring")
        self.btnMonitoring.clicked.connect(self.monitoring)
        self.btnInfo = QtWidgets.QPushButton(self.frame)
        self.btnInfo.setGeometry(QtCore.QRect(0, 344, 321, 31))
        self.btnInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInfo.setStyleSheet("color: rgb(0, 84, 139);\n"
"background-color: rgb(218, 218, 218);\n"
"font: 9pt \"Century Gothic\";")
        self.btnInfo.setAutoDefault(True)
        self.btnInfo.setDefault(False)
        self.btnInfo.setFlat(False)
        self.btnInfo.setObjectName("btnInfo")
        self.btnInfo.clicked.connect(self.info)
        self.btnReports = QtWidgets.QPushButton(self.frame)
        self.btnReports.setGeometry(QtCore.QRect(0, 380, 321, 31))
        self.btnReports.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnReports.setStyleSheet("color: rgb(0, 84, 139);\n"
"background-color: rgb(218, 218, 218);\n"
"font: 9pt \"Century Gothic\";")
        self.btnReports.setAutoDefault(True)
        self.btnReports.setDefault(False)
        self.btnReports.setFlat(False)
        self.btnReports.setObjectName("btnReports")
        self.btnReports.clicked.connect(self.report)
        self.logoutButton = QtWidgets.QPushButton(self.frame)
        self.logoutButton.setGeometry(QtCore.QRect(256, 440, 60, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.logoutButton.setFont(font)
        self.logoutButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Century Gothic\";")
        self.logoutButton.setFlat(True)
        self.logoutButton.setObjectName("logoutButton")
        self.logoutButton.clicked.connect(self.logout)
        self.changepassButton = QtWidgets.QPushButton(self.frame)
        self.changepassButton.setGeometry(QtCore.QRect(4, 440, 141, 23))
        self.changepassButton.clicked.connect(self.settings)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.changepassButton.setFont(font)
        self.changepassButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changepassButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Century Gothic\";")
        self.changepassButton.setFlat(True)
        self.changepassButton.setObjectName("changepassButton")
        self.lblInfo = QtWidgets.QLabel(self.frame)
        self.lblInfo.setGeometry(QtCore.QRect(70, 250, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblInfo.setFont(font)
        self.lblInfo.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblInfo.setLineWidth(1)
        self.lblInfo.setTextFormat(QtCore.Qt.RichText)
        self.lblInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInfo.setObjectName("lblInfo")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(16, 230, 305, 16))
        self.line_2.setMinimumSize(QtCore.QSize(305, 16))
        self.line_2.setMaximumSize(QtCore.QSize(305, 16))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(9)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(rpnrsHomeUser)
        self.label_8.setGeometry(QtCore.QRect(650, 240, 241, 191))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(0, 84, 139);\n"
"color: rgb(255, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(rpnrsHomeUser)
        self.frame_2.setGeometry(QtCore.QRect(320, 0, 621, 471))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.lblPPSS.raise_()
        self.line.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_14.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_7.raise_()
        self.frame.raise_()
        self.label_8.raise_()
        self.label_11.raise_()

        self.retranslateUi(rpnrsHomeUser)
        QtCore.QMetaObject.connectSlotsByName(rpnrsHomeUser)

    def retranslateUi(self, rpnrsHomeUser):
        _translate = QtCore.QCoreApplication.translate
        rpnrsHomeUser.setWindowTitle(_translate("rpnrsHomeUser", "RPNRS - HOME"))
        self.lblPPSS.setText(_translate("rpnrsHomeUser", "Physical Plant and Security Services"))
        self.label_6.setText(_translate("rpnrsHomeUser", "CvSU Vision"))
        self.label_5.setText(_translate("rpnrsHomeUser", "CvSU Mission"))
        self.label_11.setText(_translate("rpnrsHomeUser", "CAVITE STATE UNIVERSITY - CCAT"))
        self.label_10.setText(_translate("rpnrsHomeUser", "Republic of the Philippines"))
        self.label_13.setText(_translate("rpnrsHomeUser", "Rosario, Cavite"))
        self.label_12.setText(_translate("rpnrsHomeUser", "(FORMERLY CAVITE COLLEGE OF ARTS AND TRADES)"))
        self.label_7.setText(_translate("rpnrsHomeUser", "CAVITE STATE UNIVERSITY shall provide excellent, equitable and relevant educational opportunities in the arts, sciences, and technology through quality instruction and responsive research and development activities. It shall produce professional skilled and morally upright individuals for global competitiveness."))
        self.lblRegistered.setText(_translate("rpnrsHomeUser", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">R</span><span style=\" font-size:24pt;\">egistered</span></p></body></html>"))
        self.lblPlateNumber.setText(_translate("rpnrsHomeUser", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">P</span><span style=\" font-size:24pt;\">late </span><span style=\" font-size:36pt; font-weight:600;\">N</span><span style=\" font-size:24pt;\">umber</span></p></body></html>"))
        self.lblRecognition.setText(_translate("rpnrsHomeUser", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">R</span><span style=\" font-size:24pt;\">ecognition</span></p></body></html>"))
        self.lblSystem.setText(_translate("rpnrsHomeUser", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">S</span><span style=\" font-size:24pt;\">ystem</span></p></body></html>"))
        self.btnMonitoring.setText(_translate("rpnrsHomeUser", "MONITOR"))
        self.btnInfo.setText(_translate("rpnrsHomeUser", "VIEW INFORMATIONS"))
        self.btnReports.setText(_translate("rpnrsHomeUser", "REPORTS"))
        self.logoutButton.setText(_translate("rpnrsHomeUser", "Logout"))
        self.changepassButton.setText(_translate("rpnrsHomeUser", "Change Password"))
        self.lblInfo.setText(_translate("rpnrsHomeUser", "<html><head/><body><p><span style=\" font-weight:600;\">HOME</span></p></body></html>"))
        self.label_8.setText(_translate("rpnrsHomeUser", "The Premier University in historic Cavite recognized for excellence in the development of globally competitive and morally upright individuals."))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rpnrsHomeUser = QtWidgets.QWidget()
    ui = Ui_rpnrsHomeUser()
    ui.setupUi3(rpnrsHomeUser)
    rpnrsHomeUser.show()
    sys.exit(app.exec_())
