# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpnrsAdminSettings.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from PyQt5.QtWidgets import QMessageBox

conn = pymysql.connect(host='localhost', user='root', password='', database='rpnrsdb')

class Ui_AdminSettingsWindow(object):
    def change(self):
        oldpass = self.oldpasswordEdit.text()
        newpass = self.newpasswordEdit.text()
        cpass = self.confirmpassEdit.text()

        if oldpass == "" or newpass == "" or cpass == "":
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Please enter complete information!")
            msg.setWindowTitle("RPNRS")
            msg.exec_()
        else:

            with conn.cursor() as cursor:
                cmd = "SELECT * from acc WHERE password=%s"
                cursor.execute(cmd,(oldpass))
                if (len(cursor.fetchall())>0):
                    if newpass == cpass:
                        query = "UPDATE acc SET `password`=%s WHERE password=%s"
                        cursor.execute(query,(newpass,oldpass))
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Information)
                        msg.setText("Password successfully change.")
                        msg.setWindowTitle("RPNRS")
                        msg.exec_()
                        self.oldpasswordEdit.clear()
                        self.newpasswordEdit.clear()
                        self.confirmpassEdit.clear()
                    else:
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Critical)
                        msg.setText("New Password did not match!")
                        msg.setWindowTitle("ALERT")
                        msg.exec_()
                        self.oldpasswordEdit.clear()
                        self.newpasswordEdit.clear()
                        self.confirmpassEdit.clear()
                else:
                    msg = QMessageBox()
                    msg.setIcon(QMessageBox.Critical)
                    msg.setText("Old Password is not correct!")
                    msg.setWindowTitle("ALERT")
                    msg.exec_()
                    self.oldpasswordEdit.clear()
                    self.newpasswordEdit.clear()
                    self.confirmpassEdit.clear()
                conn.commit()
    def setupUi8(self, AdminSettingsWindow):
        AdminSettingsWindow.setObjectName("AdminSettingsWindow")
        AdminSettingsWindow.resize(588, 390)
        self.centralwidget = QtWidgets.QWidget(AdminSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 582, 392))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(0, 84, 139);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frameTitle = QtWidgets.QFrame(self.frame)
        self.frameTitle.setGeometry(QtCore.QRect(0, 0, 261, 391))
        self.frameTitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.lblRegistered = QtWidgets.QLabel(self.frameTitle)
        self.lblRegistered.setGeometry(QtCore.QRect(15, 76, 171, 58))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lblRegistered.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRegistered.setFont(font)
        self.lblRegistered.setStyleSheet("color: rgb(0, 84, 139);")
        self.lblRegistered.setTextFormat(QtCore.Qt.RichText)
        self.lblRegistered.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRegistered.setObjectName("lblRegistered")
        self.line = QtWidgets.QFrame(self.frameTitle)
        self.line.setGeometry(QtCore.QRect(0, 310, 231, 21))
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("color: rgb(0, 84, 139);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lblSystem = QtWidgets.QLabel(self.frameTitle)
        self.lblSystem.setGeometry(QtCore.QRect(10, 250, 131, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSystem.setFont(font)
        self.lblSystem.setStyleSheet("color: rgb(0, 84, 139);")
        self.lblSystem.setTextFormat(QtCore.Qt.RichText)
        self.lblSystem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSystem.setObjectName("lblSystem")
        self.lblPlateNumber = QtWidgets.QLabel(self.frameTitle)
        self.lblPlateNumber.setGeometry(QtCore.QRect(16, 130, 231, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblPlateNumber.setFont(font)
        self.lblPlateNumber.setStyleSheet("color: rgb(0, 84, 139);")
        self.lblPlateNumber.setTextFormat(QtCore.Qt.RichText)
        self.lblPlateNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPlateNumber.setObjectName("lblPlateNumber")
        self.lblRecognition = QtWidgets.QLabel(self.frameTitle)
        self.lblRecognition.setGeometry(QtCore.QRect(4, 190, 221, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRecognition.setFont(font)
        self.lblRecognition.setStyleSheet("color: rgb(0, 84, 139);")
        self.lblRecognition.setTextFormat(QtCore.Qt.RichText)
        self.lblRecognition.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRecognition.setObjectName("lblRecognition")
        self.btnChangeSave = QtWidgets.QPushButton(self.frame)
        self.btnChangeSave.setGeometry(QtCore.QRect(382, 301, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnChangeSave.setFont(font)
        self.btnChangeSave.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"color: rgb(255, 255, 255);")
        self.btnChangeSave.setAutoDefault(False)
        self.btnChangeSave.setDefault(False)
        self.btnChangeSave.setFlat(False)
        self.btnChangeSave.setObjectName("btnChangeSave")
        self.btnChangeSave.clicked.connect(self.change)
        self.confirmpassEdit = QtWidgets.QLineEdit(self.frame)
        self.confirmpassEdit.setGeometry(QtCore.QRect(292, 221, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.confirmpassEdit.setFont(font)
        self.confirmpassEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.confirmpassEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.confirmpassEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmpassEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.confirmpassEdit.setObjectName("confirmpassEdit")
        self.lblnewpass = QtWidgets.QLabel(self.frame)
        self.lblnewpass.setGeometry(QtCore.QRect(362, 181, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblnewpass.setFont(font)
        self.lblnewpass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblnewpass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblnewpass.setObjectName("lblnewpass")
        self.lblComfirmPass = QtWidgets.QLabel(self.frame)
        self.lblComfirmPass.setGeometry(QtCore.QRect(362, 251, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblComfirmPass.setFont(font)
        self.lblComfirmPass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblComfirmPass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblComfirmPass.setObjectName("lblComfirmPass")
        self.newpasswordEdit = QtWidgets.QLineEdit(self.frame)
        self.newpasswordEdit.setGeometry(QtCore.QRect(291, 144, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.newpasswordEdit.setFont(font)
        self.newpasswordEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.newpasswordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.newpasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpasswordEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.newpasswordEdit.setObjectName("newpasswordEdit")
        self.oldpasswordEdit = QtWidgets.QLineEdit(self.frame)
        self.oldpasswordEdit.setGeometry(QtCore.QRect(290, 61, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.oldpasswordEdit.setFont(font)
        self.oldpasswordEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.oldpasswordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.oldpasswordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldpasswordEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.oldpasswordEdit.setObjectName("oldpasswordEdit")
        self.lblOldPass = QtWidgets.QLabel(self.frame)
        self.lblOldPass.setGeometry(QtCore.QRect(361, 98, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblOldPass.setFont(font)
        self.lblOldPass.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblOldPass.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOldPass.setObjectName("lblOldPass")
        AdminSettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminSettingsWindow)

    def retranslateUi(self, AdminSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminSettingsWindow.setWindowTitle(_translate("AdminSettingsWindow", "Admin Settings"))
        self.lblRegistered.setText(_translate("AdminSettingsWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#00548b;\">R</span><span style=\" font-size:24pt; color:#00548b;\">egistered</span></p></body></html>"))
        self.lblSystem.setText(_translate("AdminSettingsWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">S</span><span style=\" font-size:24pt;\">ystem</span></p></body></html>"))
        self.lblPlateNumber.setText(_translate("AdminSettingsWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">P</span><span style=\" font-size:24pt;\">late </span><span style=\" font-size:36pt; font-weight:600;\">N</span><span style=\" font-size:24pt;\">umber</span></p></body></html>"))
        self.lblRecognition.setText(_translate("AdminSettingsWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">R</span><span style=\" font-size:24pt;\">ecognition</span></p></body></html>"))
        self.btnChangeSave.setText(_translate("AdminSettingsWindow", "Save"))
        self.lblnewpass.setText(_translate("AdminSettingsWindow", "New Password"))
        self.lblComfirmPass.setText(_translate("AdminSettingsWindow", "Password"))
        self.lblOldPass.setText(_translate("AdminSettingsWindow", "Old Password"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminSettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminSettingsWindow()
    ui.setupUi8(AdminSettingsWindow)
    AdminSettingsWindow.show()
    sys.exit(app.exec_())
