# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpnrsLogin.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from rpnrsHome import *
from rpnrsUserHome import *

from PyQt5.QtWidgets import QMessageBox

conn = pymysql.connect(host='localhost', user='root', password='', database='rpnrsdb')

class Ui_LoginWindow(object):
    def alert(self):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)
        msg.setText("Incorrect Password!")
        msg.setWindowTitle("ALERT")
        msg.exec_()
        self.passwordEdit.clear()
    def loginCheck(self):
        username = str(self.usernameEdit.currentText())
        password = self.passwordEdit.text()

        if username == "Physical Plant and Security Services":
            with conn.cursor() as cursor:
                cmd = "SELECT * from acc WHERE username=%s and password=%s"
                cursor.execute(cmd,(username,password))
                if (len(cursor.fetchall())>0):
                    print("Administrator Login")
                    self.rpnrsHomeWindow=QtWidgets.QMainWindow()
                    self.ui=Ui_rpnrsHomeAdmin()
                    self.ui.setupUi2(self.rpnrsHomeWindow, self.rpnrsHomeWindow)
                    self.rpnrsHomeWindow.show()
                    LoginWindow.hide()
                else:
                    self.alert()
            conn.commit()
        elif username == "Security Personnel":
            with conn.cursor() as cursor:
                cmd = "SELECT * from acc WHERE username=%s and password=%s"
                cursor.execute(cmd,(username,password))
                if (len(cursor.fetchall())>0):
                    print("Security Personnel Login")
                    self.rpnrsUserHomeWindow=QtWidgets.QMainWindow()
                    self.ui=Ui_rpnrsHomeUser()
                    self.ui.setupUi3(self.rpnrsUserHomeWindow)
                    self.rpnrsUserHomeWindow.show()
                    LoginWindow.close()
                else:
                    self.alert()
            conn.commit()
    def setupUi1(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        LoginWindow.resize(600, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setMinimumSize(QtCore.QSize(600, 410))
        LoginWindow.setMaximumSize(QtCore.QSize(600, 410))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(0, 84, 139);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblUsername = QtWidgets.QLabel(self.frame)
        self.lblUsername.setGeometry(QtCore.QRect(100, 186, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblUsername.setFont(font)
        self.lblUsername.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUsername.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.lblPassword = QtWidgets.QLabel(self.frame)
        self.lblPassword.setGeometry(QtCore.QRect(100, 256, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPassword.setObjectName("lblPassword")
        self.passwordEdit = QtWidgets.QLineEdit(self.frame)
        self.passwordEdit.setGeometry(QtCore.QRect(30, 226, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.passwordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordEdit.setObjectName("passwordEdit")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(120, 306, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"color: rgb(255, 255, 255);")
        self.btnLogin.setAutoDefault(False)
        self.btnLogin.setDefault(False)
        self.btnLogin.setFlat(False)
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.clicked.connect(self.loginCheck)
        self.usernameEdit = QtWidgets.QComboBox(self.frame)
        self.usernameEdit.setEnabled(True)
        self.usernameEdit.setGeometry(QtCore.QRect(30, 146, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.usernameEdit.setAutoFillBackground(False)
        self.usernameEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.usernameEdit.setEditable(False)
        self.usernameEdit.setObjectName("usernameEdit")
        self.usernameEdit.addItem("")
        self.usernameEdit.addItem("")
        self.lblSystem = QtWidgets.QLabel(self.frame)
        self.lblSystem.setGeometry(QtCore.QRect(329, 250, 131, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSystem.setFont(font)
        self.lblSystem.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(0, 84, 139);\n"
"background-color: rgb(255, 255, 255);")
        self.lblSystem.setTextFormat(QtCore.Qt.RichText)
        self.lblSystem.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSystem.setObjectName("lblSystem")
        self.lblRecognition = QtWidgets.QLabel(self.frame)
        self.lblRecognition.setGeometry(QtCore.QRect(323, 190, 221, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRecognition.setFont(font)
        self.lblRecognition.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(0, 84, 139);\n"
"background-color: rgb(255, 255, 255);")
        self.lblRecognition.setTextFormat(QtCore.Qt.RichText)
        self.lblRecognition.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRecognition.setObjectName("lblRecognition")
        self.lblPlateNumber = QtWidgets.QLabel(self.frame)
        self.lblPlateNumber.setGeometry(QtCore.QRect(335, 130, 231, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblPlateNumber.setFont(font)
        self.lblPlateNumber.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(0, 84, 139);\n"
"background-color: rgb(255, 255, 255);")
        self.lblPlateNumber.setTextFormat(QtCore.Qt.RichText)
        self.lblPlateNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPlateNumber.setObjectName("lblPlateNumber")
        self.frameTitle = QtWidgets.QFrame(self.frame)
        self.frameTitle.setGeometry(QtCore.QRect(321, 0, 261, 391))
        self.frameTitle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.lblRegistered = QtWidgets.QLabel(self.frameTitle)
        self.lblRegistered.setGeometry(QtCore.QRect(15, 76, 171, 58))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 84, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lblRegistered.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRegistered.setFont(font)
        self.lblRegistered.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(0, 84, 139);\n"
"background-color: rgb(255, 255, 255);")
        self.lblRegistered.setTextFormat(QtCore.Qt.RichText)
        self.lblRegistered.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRegistered.setObjectName("lblRegistered")
        self.line = QtWidgets.QFrame(self.frameTitle)
        self.line.setGeometry(QtCore.QRect(0, 310, 231, 21))
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet("color: rgb(0, 84, 139);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.lblSystem_2 = QtWidgets.QLabel(self.frame)
        self.lblSystem_2.setGeometry(QtCore.QRect(97, 35, 131, 58))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblSystem_2.setFont(font)
        self.lblSystem_2.setStyleSheet("font: 16pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.lblSystem_2.setTextFormat(QtCore.Qt.RichText)
        self.lblSystem_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSystem_2.setObjectName("lblSystem_2")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(97, 84, 131, 21))
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.frameTitle.raise_()
        self.lblUsername.raise_()
        self.lblPassword.raise_()
        self.passwordEdit.raise_()
        self.btnLogin.raise_()
        self.usernameEdit.raise_()
        self.lblSystem.raise_()
        self.lblRecognition.raise_()
        self.lblPlateNumber.raise_()
        self.lblSystem_2.raise_()
        self.line_2.raise_()
        self.verticalLayout.addWidget(self.frame)
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.usernameEdit.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "RPNRS - LOGIN"))
        self.lblUsername.setText(_translate("LoginWindow", "Username"))
        self.lblPassword.setText(_translate("LoginWindow", "Password"))
        self.btnLogin.setText(_translate("LoginWindow", "Login"))
        self.usernameEdit.setItemText(0, _translate("LoginWindow", "Physical Plant and Security Services"))
        self.usernameEdit.setItemText(1, _translate("LoginWindow", "Security Personnel"))
        self.lblSystem.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">S</span><span style=\" font-size:24pt;\">ystem</span></p></body></html>"))
        self.lblRecognition.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">R</span><span style=\" font-size:24pt;\">ecognition</span></p></body></html>"))
        self.lblPlateNumber.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">P</span><span style=\" font-size:24pt;\">late </span><span style=\" font-size:36pt; font-weight:600;\">N</span><span style=\" font-size:24pt;\">umber</span></p></body></html>"))
        self.lblRegistered.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#00548b;\">R</span><span style=\" font-size:24pt; color:#00548b;\">egistered</span></p></body></html>"))
        self.lblSystem_2.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">LOGIN</span></p></body></html>"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi1(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
